buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // 使用 7.x 版本的插件比较稳妥，适配 JDK 11/17
        classpath "com.android.tools.build:gradle:8.1.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}