plugins {
    id 'com.android.application'
}

android {
    namespace 'net.micode.notes' // 需与原项目 Manifest 里的 package 一致
    compileSdk 33

    defaultConfig {
        applicationId "net.micode.notes"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    useLibrary 'org.apache.http.legacy'
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}